export type Nav = 'Home' | 'Intelligence' | 'Work' | 'Activity';
export type StoryStatus = 'draft' | 'ready' | 'in-progress' | 'awaiting-delegation-approval' | 'delegated' | 'awaiting-validation' | 'review-required' | 'completed' | 'blocked' | 'paused' | 'cancelled' | 'superseded' | 'handed-off';
export interface EvidenceItem { id?: string; kind: string; label: string; path?: string; okfId?: string; confidence?: number; summary?: string; }
export interface LanguageCapability { id: string; label: string; level: string; extensions: readonly string[]; files?: number; baseline?: string; semanticProvider?: string; semanticFiles?: number; deterministicFiles?: number; failedSemanticFiles?: number; capabilities?: Record<string, boolean>; warnings?: readonly string[]; frontend?: string; }
export interface OkfSummary { profile: string; version: string; extractionRunId: string; units: number; relationships: number; observations: number; evidence: number; active: number; deleted: number; graphNodes: number; graphEdges: number; cpgBindings: number; validated: boolean; portableBundle?: { path: string; conceptFiles: number; validated: boolean; profile: string; generatedAt: string }; evidenceSamples: Array<{ id: string; path: string; method: string; observedAt: string }>; }
export interface IntelligenceSummary { fileCount?: number; projectTypes?: string[]; architecture?: string; git?: { branch?: string; changedFiles?: string[] }; languageCapabilities?: LanguageCapability[]; universalTextFiles?: number; okf?: OkfSummary; stages?: Array<{ id: string; label: string; status: string; progress?: number; itemCount?: number; durationMs?: number }>; families?: Array<{ id: string; label: string; status?: string; itemCount?: number }>; }
export interface ContextSection { path: string; reason: string; preview: string; estimatedTokens: number; score?: number; evidence?: EvidenceItem[]; }
export interface TaskResult { intentType?: string; route?: string; reason?: string; tokenReduction?: number; relevantFiles: string[]; relevantSymbols: string[]; relatedTests: string[]; missingTests: string[]; qaChecklist: string[]; securityRisk: string; performanceRisk: string; modernizationNotes: string[]; copilotPrompt: string; prMarkdown?: string; validationCommands?: string[]; contextTokens?: { raw: number; selected: number; prompt: number; packets: number; tier: string }; contextManifest?: { delegationTokenBudget: number; usedTokens: number; selectedFiles: number; omittedFiles: number; protectedFiles: number; traceableEvidence: number; generatedAt: string }; contextSections?: ContextSection[]; omittedContext?: Array<{ path: string; reason: string; estimatedTokens: number }>; relatedApis?: string[]; impactedServices?: string[]; architectureConstraints?: string[]; securityConstraints?: string[]; performanceConstraints?: string[]; acceptanceCriteria?: string[]; repoSkills?: Array<{ id: string; name: string; description: string; guidance: string[] }>; evidence?: EvidenceItem[]; taskWorkspace?: { id?: string; name?: string }; }
export interface ResearchDocument { title: string; problemStatement: string; markdown: string; evidenceMatrix: EvidenceItem[]; affectedArchitecture: string[]; affectedFlows: string[]; affectedTests: string[]; risks: string[]; constraints: string[]; unknowns: string[]; }
export interface BacklogStory { id: string; kind: 'user-story' | 'quality-story'; title: string; description: string; acceptanceCriteria: string[]; evidence: string[]; dependencies: string[]; status: string; scope?: { files?: string[]; symbols?: string[]; interfaces?: string[] }; }
export interface Story { id: string; type: string; title: string; objective: string; status: StoryStatus; dependencies: string[]; acceptanceCriteria: string[]; satisfiedCriteria: string[]; evidence: string[]; blockers: string[]; decisions: string[]; validationRuns?: Array<{ id: string; status: string; commands: string[]; evidence: string[] }>; findings?: Array<{ id: string; kind: string; severity: string; summary: string; status: string; evidence: string[] }>; delegation?: { id: string; status: string; agent: string; skills: string[]; instructions: string[] }; }
export interface SdlcPlan { id: string; intent: string; specificationStatus: string; source?: { kind: string; featureId?: string; featureName?: string }; researchDocument: ResearchDocument; backlogStories: BacklogStory[]; stories: Story[]; }
export interface Operation { id: string; kind: string; status: string; progress: number; message: string; updatedAt: string; }
export interface ApplicationState { version: number; status: string; workspace?: { name: string; root: string; branch?: string }; intelligence?: IntelligenceSummary; taskAnalysis?: TaskResult; sdlc?: SdlcPlan; intelligenceActivity?: Array<{ id?: string; timestamp: string; type: string; message: string; progress?: number }>; operations?: Operation[]; handoffs?: unknown[]; notification?: { level: string; message: string }; }
