import type { IntelligenceStore } from "../persistence/IntelligenceStore";
import type { WorkflowService } from "../workflow/WorkflowService";
import type { ImpactQaAggregate, Phase7QaExecution } from "../../shared/contracts/impactQa";
import { WorkspaceChangeSetService, type WorkspaceChangeSetProvider } from "./WorkspaceChangeSetService";
import { ChangedSymbolResolver } from "./ChangedSymbolResolver";
import { Phase7ImpactAnalysisService } from "./Phase7ImpactAnalysisService";
import { TestFrameworkDiscoveryService } from "./TestFrameworkDiscoveryService";
import { QaPlanService } from "./QaPlanService";
import { ControlledCommandRunner } from "./ControlledCommandRunner";
import { TestResultParserService } from "./TestResultParserService";
import { QaDecisionService } from "./QaDecisionService";
import { ImpactQaPersistence } from "./ImpactQaPersistence";

export interface ImpactQaHost { workspaceFiles(): Promise<Set<string>>; pickChangedFiles(): Promise<string[]>; openSource(path: string): Promise<void> }
export class ImpactQaService {
  private readonly changes: WorkspaceChangeSetService; private readonly runner: ControlledCommandRunner; private readonly plans = new QaPlanService(); private readonly parsers = new TestResultParserService(); private readonly decisions = new QaDecisionService();
  constructor(private readonly root: string, private readonly persistence: ImpactQaPersistence, private readonly workflows: WorkflowService, private readonly intelligence: IntelligenceStore, provider: WorkspaceChangeSetProvider, private readonly host: ImpactQaHost) { this.changes = new WorkspaceChangeSetService(provider); this.runner = new ControlledCommandRunner(root); }
  async initialize(): Promise<void> { await this.persistence.initialize(); }
  async load(workflowId: string): Promise<ImpactQaAggregate> { this.assertWorkflow(workflowId); return this.persistence.get(workflowId) ?? { workflowId, changedEntities: [], capabilities: [] }; }
  async detect(workflowId: string, manualSelection = false): Promise<ImpactQaAggregate> { const current = await this.load(workflowId); const manualFiles = manualSelection ? await this.host.pickChangedFiles() : undefined; try { const changeSet = await this.changes.detect({ workflowId, workspaceFiles: await this.host.workspaceFiles(), manualFiles }); const next = { ...current, changeSet, changedEntities: [], impactAnalysis: undefined, qaPlan: undefined, execution: undefined, decision: undefined, detectionMessage: `Detected ${changeSet.files.length} changed file(s) from ${changeSet.source}.` }; await this.persistence.save(next); return next; } catch (cause) { if (!manualSelection && cause instanceof Error && "code" in cause && cause.code === "change-detection-unavailable") { const next = { ...current, detectionMessage: cause.message }; await this.persistence.save(next); return next; } throw cause; } }
  async openChangedFile(workflowId: string, path: string): Promise<void> { const state = await this.load(workflowId); if (!state.changeSet?.files.some((item) => item.path === path)) throw Object.assign(new Error("Changed file does not belong to this change set."), { code: "file-outside-workspace" }); await this.host.openSource(path); }
  async acceptChangeSet(workflowId: string, expectedHash: string): Promise<ImpactQaAggregate> { const state = await this.load(workflowId); if (!state.changeSet || state.changeSet.contentHash !== expectedHash) throw Object.assign(new Error("Change set is stale."), { code: "change-set-stale" }); const snapshot = this.snapshot(); const changedEntities = new ChangedSymbolResolver(snapshot).resolve(state.changeSet, revision(snapshot)); const next = { ...state, changeSet: { ...state.changeSet, status: "ready" as const }, changedEntities }; await this.persistence.save(next); return next; }
  async analyze(workflowId: string, expectedHash: string): Promise<ImpactQaAggregate> { const state = await this.load(workflowId); if (!state.changeSet || state.changeSet.status !== "ready" || state.changeSet.contentHash !== expectedHash) throw Object.assign(new Error("Accept the current change set before analysis."), { code: "change-set-stale" }); const snapshot = this.snapshot(); const changedEntities = state.changedEntities.length ? state.changedEntities : new ChangedSymbolResolver(snapshot).resolve(state.changeSet, revision(snapshot)); const impactAnalysis = new Phase7ImpactAnalysisService(snapshot).analyze({ workflowId, changeSet: state.changeSet, changedEntities, intelligenceRevision: revision(snapshot), depth: 3, maxNodes: 75, maxEdges: 150 }); const capabilities = await new TestFrameworkDiscoveryService().discover(this.root); const next = { ...state, changedEntities, impactAnalysis, capabilities, qaPlan: undefined, execution: undefined, decision: undefined }; await this.persistence.save(next); return next; }
  async acceptImpact(workflowId: string, impactId: string, expectedHash: string): Promise<ImpactQaAggregate> { const state = await this.load(workflowId); const currentRevision = revision(this.snapshot()); if (!state.impactAnalysis || state.impactAnalysis.id !== impactId || state.impactAnalysis.contentHash !== expectedHash || state.impactAnalysis.intelligenceRevision !== currentRevision) throw Object.assign(new Error("Impact analysis is stale because its content or intelligence revision changed."), { code: "intelligence-stale" }); const impactAnalysis = { ...state.impactAnalysis, status: "accepted" as const }; await this.workflows.acceptImpactAnalysisStage(workflowId); const next = { ...state, impactAnalysis }; await this.persistence.save(next); return next; }
  async generatePlan(workflowId: string): Promise<ImpactQaAggregate> { const state = await this.load(workflowId); if (!state.changeSet || state.impactAnalysis?.status !== "accepted") throw Object.assign(new Error("Accept current impact analysis before QA planning."), { code: "impact-analysis-failed" }); const qaPlan = this.plans.generate({ workflowId, impactAnalysisId: state.impactAnalysis.id, impactHash: state.impactAnalysis.contentHash, changeSetHash: state.changeSet.contentHash, mappings: state.impactAnalysis.mappedTests, capabilities: state.capabilities, coverageGaps: state.impactAnalysis.coverageGaps }); const next = { ...state, qaPlan, execution: undefined, decision: undefined }; await this.persistence.save(next); return next; }
  async updatePlan(workflowId: string, itemId: string, selected: boolean, reason?: string): Promise<ImpactQaAggregate> { const state = await this.load(workflowId); if (!state.qaPlan) throw Object.assign(new Error("QA plan is unavailable."), { code: "qa-plan-empty" }); const qaPlan = this.plans.updateSelection(state.qaPlan, itemId, selected, reason); const next = { ...state, qaPlan, execution: undefined, decision: undefined }; await this.persistence.save(next); return next; }
  async approvePlan(workflowId: string, expectedHash: string): Promise<ImpactQaAggregate> { const state = await this.load(workflowId); if (!state.qaPlan || state.qaPlan.contentHash !== expectedHash) throw Object.assign(new Error("QA plan is stale."), { code: "qa-plan-stale" }); const next = { ...state, qaPlan: this.plans.approve(state.qaPlan) }; await this.persistence.save(next); return next; }
  async execute(workflowId: string, qaPlanId: string, onProgress?: (event: { executionId: string; commandId: string; output?: string; source?: "stdout" | "stderr"; completed: number; total: number; status: string }) => void): Promise<ImpactQaAggregate> { const state = await this.load(workflowId); if (!state.qaPlan || state.qaPlan.id !== qaPlanId || state.qaPlan.status !== "approved") throw Object.assign(new Error("Explicit approval of the current QA plan is required."), { code: "command-approval-required" }); if (!state.changeSet || !state.impactAnalysis || state.impactAnalysis.status !== "accepted" || state.qaPlan.changeSetHash !== state.changeSet.contentHash || state.qaPlan.impactHash !== state.impactAnalysis.contentHash || state.impactAnalysis.intelligenceRevision !== revision(this.snapshot())) throw Object.assign(new Error("The QA plan is stale. Refresh impact analysis and approve the updated commands."), { code: "qa-plan-stale" }); const selected = [...state.qaPlan.requiredItems, ...state.qaPlan.recommendedItems, ...state.qaPlan.optionalItems].filter((item) => item.selected); const execution: Phase7QaExecution = { id: crypto.randomUUID(), workflowId, qaPlanId, commandRuns: [], parsedResults: [], status: "running", startedAt: new Date().toISOString() }; await this.persistence.save({ ...state, qaPlan: { ...state.qaPlan, status: "executing" }, execution }); for (const item of selected) { onProgress?.({ executionId: execution.id, commandId: item.command.id, completed: execution.commandRuns.length, total: selected.length, status: "running" }); const result = await this.runner.run(item.command, { onOutput: (output, source) => onProgress?.({ executionId: execution.id, commandId: item.command.id, output, source, completed: execution.commandRuns.length, total: selected.length, status: "running" }) }); execution.commandRuns.push(result); execution.parsedResults.push(this.parsers.parse(state.capabilities.find((capability) => capability.id === item.command.frameworkId)?.framework ?? "unknown", result.rawOutput, "", result.exitCode)); if (result.status !== "completed") break; }
    execution.completedAt = new Date().toISOString(); execution.status = execution.commandRuns.some((item) => item.status === "cancelled") ? "cancelled" : execution.commandRuns.some((item) => item.status !== "completed") ? "failed" : "completed"; const required = state.qaPlan.requiredItems.filter((item) => item.selected); const requiredRuns = required.map((item) => execution.commandRuns.find((run) => run.commandDefinitionId === item.command.id)); const blocking = state.impactAnalysis?.coverageGaps.filter((gap) => gap.blocking).map((gap) => gap.id) ?? []; const warnings = state.impactAnalysis?.coverageGaps.filter((gap) => !gap.blocking).map((gap) => gap.id) ?? []; const decision = this.decisions.decide({ workflowId, qaPlanId, qaExecutionId: execution.id, planCurrent: true, impactCurrent: state.impactAnalysis?.status === "accepted", requiredExecuted: requiredRuns.every(Boolean), requiredPassed: requiredRuns.every((run) => run?.status === "completed"), executionSucceeded: execution.status === "completed", blockingGapIds: blocking, warningGapIds: warnings, optionalSkipped: state.qaPlan.optionalItems.some((item) => !item.selected), cancelled: execution.status === "cancelled", evidenceIds: execution.commandRuns.map((item) => item.id) }); const final = { ...state, qaPlan: { ...state.qaPlan, status: "completed" as const }, execution, decision }; await this.persistence.save(final); if (decision.decision === "passed" || decision.decision === "passed-with-warnings") await this.workflows.completeQaStage(workflowId); onProgress?.({ executionId: execution.id, commandId: "", completed: execution.commandRuns.length, total: selected.length, status: execution.status }); return final; }
  cancel(commandId: string): boolean { return this.runner.cancel(commandId); }
  private snapshot() { const snapshot = this.intelligence.getSnapshot(); if (!snapshot) throw Object.assign(new Error("Repository Intelligence is not ready."), { code: "intelligence-not-ready" }); return snapshot; }
  private assertWorkflow(workflowId: string): void { if (!this.workflows.getWorkflow(workflowId)) throw Object.assign(new Error("Workflow was not found."), { code: "internal-error" }); }
}
function revision(snapshot: ReturnType<IntelligenceStore["getSnapshot"]> & {}) { return `generation:${snapshot.manifest.generation}:scan:${snapshot.manifest.scanRevision}`; }
