import { createHash } from "node:crypto";
import type { QaCoverageGap, QaPlan, QaTestMapping, QaPlanItem, TestFrameworkCapability } from "../../shared/contracts/impactQa";

export class QaPlanService {
  generate(input: { workflowId: string; impactAnalysisId: string; impactHash: string; changeSetHash: string; mappings: QaTestMapping[]; capabilities: TestFrameworkCapability[]; coverageGaps: QaCoverageGap[] }): QaPlan {
    const command = input.capabilities.flatMap((item) => item.commands).find(Boolean);
    if (!command) throw Object.assign(new Error("No verified test command is available."), { code: "test-command-unavailable" });
    const unique = [...new Map(input.mappings.map((mapping) => [mapping.testFilePath, mapping])).values()];
    const items = unique.map<QaPlanItem>((mapping) => { const category = mapping.distance === 0 && mapping.confidence >= .8 ? "required" : mapping.distance <= 2 && mapping.confidence >= .6 ? "recommended" : "optional"; return { id: `qa-item:${mapping.id}`, testFilePath: mapping.testFilePath, label: mapping.testFilePath, layer: layer(mapping.testFilePath), command: { ...command, id: `${command.id}:file:${mapping.testFilePath}`, arguments: [...command.arguments, mapping.testFilePath] }, reason: category === "required" ? "Direct evidence-backed mapping to changed code." : category === "recommended" ? "Evidence-backed mapping to a broader or transitive impact." : "Useful bounded regression coverage with indirect evidence.", affectedEntityIds: [mapping.productionEntityId], confidence: mapping.confidence, category, selected: category !== "optional" }; });
    items.push({ id: "qa-item:repository-regression", label: "Repository regression suite", layer: "regression", command: { ...command, id: `${command.id}:repository`, scope: "repository" }, reason: "Optional broader repository regression; not selected automatically.", affectedEntityIds: [], confidence: .5, category: "optional", selected: false });
    const timestamp = new Date().toISOString(); const grouped = { requiredItems: items.filter((item) => item.category === "required"), recommendedItems: items.filter((item) => item.category === "recommended"), optionalItems: items.filter((item) => item.category === "optional") };
    const contentHash = hash({ impact: input.impactHash, change: input.changeSetHash, items: items.map((item) => [item.id, item.selected, item.command]) });
    return { id: crypto.randomUUID(), workflowId: input.workflowId, impactAnalysisId: input.impactAnalysisId, impactHash: input.impactHash, changeSetHash: input.changeSetHash, ...grouped, coverageGapIds: input.coverageGaps.map((item) => item.id), status: "ready-for-review", createdAt: timestamp, contentHash };
  }
  updateSelection(plan: QaPlan, itemId: string, selected: boolean, overrideReason?: string): QaPlan { const all = [...(plan.requiredItems ?? []), ...(plan.recommendedItems ?? []), ...(plan.optionalItems ?? [])]; const current = all.find((item) => item.id === itemId); if (!current) throw new Error("QA plan item was not found."); if (!selected && current.category === "required" && !overrideReason?.trim()) throw new Error("Required tests need an explicit override reason."); const update = (items: QaPlanItem[]) => items.map((item) => item.id === itemId ? { ...item, selected, overrideReason: overrideReason?.trim() || undefined } : item); const next = { ...plan, requiredItems: update(plan.requiredItems), recommendedItems: update(plan.recommendedItems), optionalItems: update(plan.optionalItems), status: "ready-for-review" as const }; return { ...next, contentHash: hash({ previous: plan.contentHash, itemId, selected, overrideReason }) }; }
  approve(plan: QaPlan): QaPlan { if (![...plan.requiredItems, ...plan.recommendedItems, ...plan.optionalItems].some((item) => item.selected)) throw Object.assign(new Error("QA plan has no selected tests."), { code: "qa-plan-empty" }); return { ...plan, status: "approved" }; }
  freshness(saved: { changeSetHash: string; impactHash: string }, current: { changeSetHash: string; impactHash: string }): { stale: boolean; reason?: string } { if (saved.changeSetHash !== current.changeSetHash) return { stale: true, reason: "Change set changed; refresh impact analysis and QA plan." }; if (saved.impactHash !== current.impactHash) return { stale: true, reason: "Impact analysis changed; regenerate the QA plan." }; return { stale: false }; }
}
function layer(path: string): string { return /e2e/i.test(path) ? "e2e" : /integration/i.test(path) ? "integration" : "unit"; }
function hash(value: unknown): string { return `sha256:${createHash("sha256").update(JSON.stringify(value)).digest("hex")}`; }
