import { useState } from "react";
import type { DevelopmentAggregate } from "../../../shared/contracts/development";
import type { HostBridge } from "../../services/HostBridge";

export function DevelopmentContextPackage({ bridge, state, notes, onChange, onError }: { bridge: HostBridge; state: DevelopmentAggregate; notes: string; onChange: (value: DevelopmentAggregate, notice: string) => void; onError: (error: unknown) => void }): React.JSX.Element {
  const [budget, setBudget] = useState(state.contextPackage?.budget.requestedTokens ?? 12_000);
  const [busy, setBusy] = useState(false); const pkg = state.contextPackage; const ids = { workflowId: state.workflow.id, workItemId: state.workItem.id };
  const act = async (operation: () => Promise<DevelopmentAggregate>, notice: string) => { setBusy(true); try { onChange(await operation(), notice); } catch (cause) { onError(cause); } finally { setBusy(false); } };
  const revision = pkg ? { packageId: pkg.id, revision: pkg.metadata.version } : undefined;
  const editable = Boolean(pkg && !["approved", "superseded", "delegated"].includes(pkg.metadata.status));
  const pinnedItemIds = pkg?.items.filter((item) => item.pinned).map((item) => item.id) ?? [];
  return <section className="development-section context-package-section" aria-labelledby="development-context-package"><header><div><span className="eyebrow">4</span><h2 id="development-context-package">Context Package</h2></div><span className="status-pill">{pkg?.metadata.status ?? "not built"}</span></header>
    <p className="section-intro">Build a measured, compressed package from the current Development inputs. Only an approved persisted revision can enter the final prompt.</p>
    <div className="context-budget-row"><label className="field-stack"><strong>Token budget</strong><input aria-label="Context token budget" type="number" min={500} max={1_000_000} value={budget} onChange={(event) => setBudget(Number(event.target.value))} /></label><button className="primary-button" disabled={busy || budget < 500} onClick={() => void act(() => bridge.request("development.context.build", { correlationId: crypto.randomUUID(), ...ids, budgetTokens: budget, ...(notes.trim() ? { notes: notes.trim() } : {}), pinnedItemIds }), pkg ? "Context package regenerated as a new revision." : "Context package built from current Development inputs.")}>{pkg ? "Regenerate Context" : "Build Context"}</button>{pkg && <button className="ghost-button" disabled={busy || budget === pkg.budget.requestedTokens} onClick={() => void act(() => bridge.request("development.context.changeBudget", { correlationId: crypto.randomUUID(), ...ids, ...revision!, budgetTokens: budget, ...(notes.trim() ? { notes: notes.trim() } : {}), pinnedItemIds }), "Budget applied and context regenerated.")}>Apply Budget</button>}</div>
    {!pkg && <p className="bounded-empty">No context package yet. Save a valid execution profile and select real source scope, then build context.</p>}
    {pkg && <>
      <div className="context-metrics" aria-label="Context token metrics"><div><strong>{pkg.rawBaseline.tokenCount.toLocaleString()}</strong><span>Raw tokens</span></div><div><strong>{pkg.compressed.tokenCount.toLocaleString()}</strong><span>Compressed tokens</span></div><div><strong>{pkg.compressed.reductionTokens.toLocaleString()}</strong><span>Tokens saved</span></div><div><strong>{pkg.compressed.reductionPercentage.toFixed(1)}%</strong><span>Reduction</span></div></div>
      <div className="prompt-meta"><span>{pkg.rawBaseline.tokenizer.measurement === "exact-local" ? "Exact · Keystone local tokenizer" : "Estimated · fallback tokenizer"}</span><span>{pkg.rawBaseline.tokenizer.id}</span><span>Package {pkg.id.slice(0, 8)} · revision {pkg.metadata.version}</span></div>
      <details open><summary>Raw baseline sources ({pkg.rawBaseline.sources.length})</summary><ul className="context-source-list">{pkg.rawBaseline.sources.map((source) => <li key={source}>{source}</li>)}</ul></details>
      <details open><summary>Included and summarized ({pkg.items.length})</summary><ul className="context-item-list">{pkg.items.map((item) => <li key={item.id}><div><strong>{item.title}</strong><span>{item.sourceType} · {item.contentMode} · {item.tokenCount} tokens</span><small>{item.reasons.join(" ")}</small><pre>{item.content}</pre></div>{editable && <div className="button-row"><button className="ghost-button" onClick={() => void act(() => bridge.request("development.context.pin", { correlationId: crypto.randomUUID(), ...ids, ...revision!, itemId: item.id, pinned: !item.pinned }), item.pinned ? "Context item unpinned." : "Context item pinned.")}>{item.pinned ? "Unpin" : "Pin"}</button><button className="ghost-button danger" onClick={() => void act(() => bridge.request("development.context.remove", { correlationId: crypto.randomUUID(), ...ids, ...revision!, itemId: item.id, overrideRequired: item.importance === "required" }), "Context item removed; completeness recalculated.")}>Remove</button></div>}</li>)}</ul></details>
      <details><summary>Excluded ({pkg.exclusions.length})</summary>{pkg.exclusions.length ? <ul className="context-item-list">{pkg.exclusions.map((entry) => <li key={`${entry.item.id}:${entry.reason}`}><div><strong>{entry.item.title}</strong><span>{entry.reason} · {entry.tokensRemoved} tokens</span><small>{entry.detail ?? entry.item.reasons.join(" ")}</small></div>{editable && entry.restorable && <button className="ghost-button" onClick={() => void act(() => bridge.request("development.context.restore", { correlationId: crypto.randomUUID(), ...ids, ...revision!, itemId: entry.item.id }), "Context item restored.")}>Restore</button>}</li>)}</ul> : <p className="bounded-empty">No exclusions.</p>}</details>
      <details open><summary>Completeness · {(pkg.coverage.completenessScore * 100).toFixed(0)}%</summary><ul className="fact-list">{pkg.requiredFacts.map((fact) => <li key={fact.id} className={fact.state !== "satisfied" ? "unavailable" : undefined}><strong>{fact.description}</strong><span>{fact.state}{fact.critical ? " · critical" : ""}</span><small>{fact.reason}</small></li>)}</ul></details>
      {pkg.warnings.length > 0 && <ul className="completion-gates">{pkg.warnings.map((warning, index) => <li key={`${warning.code}:${index}`}>{warning.severity}: {warning.message}</li>)}</ul>}
      <div className="button-row"><button className="primary-button" disabled={busy || pkg.metadata.status !== "ready" || pkg.coverage.unresolvedRequiredFacts.length > 0} onClick={() => void act(() => bridge.request("development.context.approve", { correlationId: crypto.randomUUID(), ...ids, ...revision!, fingerprint: pkg.metadata.contentHash }), "Context package approved. Prompt preparation is now available.")}>Approve Context</button>{pkg.metadata.status === "approved" && <span className="success-inline">Approved revision {pkg.metadata.version} · SHA-256 {pkg.metadata.contentHash.slice(0, 12)}…</span>}</div>
    </>}
  </section>;
}
