import { useCallback, useEffect, useMemo, useState } from "react";
import type { ExecutionConfigurationAggregate, InstructionPreview, SkillDefinition } from "../../../shared/contracts/executionConfiguration";
import type { HostBridge } from "../../services/HostBridge";

// This bounded editor renders the full dependent selection state in one accessible form.
// eslint-disable-next-line complexity
export function ExecutionConfiguration({ bridge, workflowId, workItemId, onProfileChange }: { bridge: HostBridge; workflowId: string; workItemId: string; onProfileChange: () => void }): React.JSX.Element {
  const [state, setState] = useState<ExecutionConfigurationAggregate>();
  const [mode, setMode] = useState(""); const [agent, setAgent] = useState(""); const [skill, setSkill] = useState(""); const [instructions, setInstructions] = useState<string[]>([]);
  const [preview, setPreview] = useState<InstructionPreview>(); const [skillPreview, setSkillPreview] = useState<SkillDefinition>(); const [showAgentForm, setShowAgentForm] = useState(false); const [editingAgentId, setEditingAgentId] = useState<string>();
  const [agentForm, setAgentForm] = useState({ displayName: "", chatCommandId: "", usageNote: "" }); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>(); const [notice, setNotice] = useState<string>();
  const ids = useMemo(() => ({ workflowId, workItemId }), [workflowId, workItemId]);

  const accept = useCallback((next: ExecutionConfigurationAggregate) => { setState(next); if (next.profile) { setMode(next.profile.executionCapabilityId); setAgent(next.profile.agentConfigurationId ?? ""); setSkill(next.profile.skillId); setInstructions(next.profile.instructionIds); } }, []);
  const checkConflicts = useCallback((nextIds: string[]) => { void bridge.request("executionConfiguration.detectConflicts", { correlationId: crypto.randomUUID(), ...ids, instructionIds: nextIds }).then((next) => setState((current) => current ? { ...current, conflicts: next.conflicts } : next)).catch((cause) => setError(cause instanceof Error ? cause.message : String(cause))); }, [bridge, ids]);
  const run = useCallback(async (operation: () => Promise<ExecutionConfigurationAggregate>, success?: string) => { setBusy(true); setError(undefined); setNotice(undefined); try { accept(await operation()); if (success) setNotice(success); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } }, [accept]);
  useEffect(() => { queueMicrotask(() => void run(() => bridge.request("executionConfiguration.load", { correlationId: crypto.randomUUID(), ...ids }))); }, [bridge, ids, run]);

  if (!state) return <section className="development-section execution-configuration" aria-labelledby="execution-configuration"><header><div><span className="eyebrow">3</span><h2 id="execution-configuration">Execution Configuration</h2></div><span>loading</span></header></section>;
  const selectedSources = state.instructions.filter((item) => instructions.includes(item.id)); const blockingConflict = state.conflicts.some((item) => item.severity === "error");
  const selectionUnavailable = selectedSources.some((item) => item.availability !== "available"); const selectedMode = state.capabilities.find((item) => item.id === mode);
  const selectedDiscoveredAgent = state.agents.find((item) => item.id === agent); const selectedManualAgent = state.manualAgents.find((item) => item.id === agent); const selectedSkill = state.skills.find((item) => item.id === skill);
  const valid = Boolean(selectedMode?.availability === "available" && skill && !selectionUnavailable && !blockingConflict);
  const dirty = !state.profile || mode !== state.profile.executionCapabilityId || agent !== (state.profile.agentConfigurationId ?? "") || skill !== state.profile.skillId || JSON.stringify([...instructions].sort()) !== JSON.stringify([...state.profile.instructionIds].sort());
  const reset = () => { setMode(state.profile?.executionCapabilityId ?? ""); setAgent(state.profile?.agentConfigurationId ?? ""); setSkill(state.profile?.skillId ?? ""); setInstructions(state.profile?.instructionIds ?? []); setError(undefined); };

  return <section className="development-section execution-configuration" aria-labelledby="execution-configuration"><header><div><span className="eyebrow">3</span><h2 id="execution-configuration">Execution Configuration</h2></div><span>{state.profile?.status ?? "not saved"}</span></header>
    {error && <div className="error-banner" role="alert"><strong>{error}</strong></div>}{notice && <div className="success-banner" role="status">{notice}</div>}
    <div className="configuration-block"><h3>Execution mode</h3><div className="execution-mode-grid">{state.capabilities.map((item) => <label key={item.id} className={`configuration-choice ${mode === item.id ? "selected" : ""} ${item.availability !== "available" ? "unavailable" : ""}`}><input type="radio" name="execution-mode" aria-label={item.displayName} checked={mode === item.id} disabled={item.availability !== "available" || busy} onChange={() => { setMode(item.id); if (item.kind === "manual-work") setAgent(""); }} /><strong>{item.displayName}</strong><small>{item.availability} · {item.source}</small>{item.diagnostic && <span className="capability-diagnostic">{item.diagnostic.message}</span>}</label>)}</div></div>
    <div className="configuration-block"><div className="configuration-title-row"><h3>Agent</h3><button className="ghost-button" onClick={() => setShowAgentForm((value) => !value)}>Add Manual Agent</button></div>
      <p className="configuration-note">An agent label is optional for clipboard handoff and is never treated as proof of invocation.</p>
      <label className="field-stack"><strong>Existing agent</strong><select aria-label="Agent" value={agent} disabled={selectedMode?.kind === "manual-work" || busy} onChange={(event) => setAgent(event.target.value)}><option value="">No agent</option>{state.agents.length > 0 && <optgroup label="Discovered agents">{state.agents.map((item) => <option key={item.id} value={item.id} disabled={item.availability !== "available"}>{item.displayName}</option>)}</optgroup>}{state.manualAgents.length > 0 && <optgroup label="Manual agents">{state.manualAgents.map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</optgroup>}</select></label>
      {selectedDiscoveredAgent && <p className="configuration-note">{selectedDiscoveredAgent.displayName} · discovered · {selectedDiscoveredAgent.supportedInvocationModes.join(", ")}</p>}
      {selectedManualAgent && <p className="manual-agent-warning">This agent is manually configured. Keystone can prepare the prompt, but execution depends on the selected handoff mode.</p>}
      {state.manualAgents.length > 0 && <div className="configuration-list">{state.manualAgents.map((item) => <div key={item.id} className="configuration-choice"><strong>{item.displayName}</strong><small>{item.chatCommandId ? `${item.chatCommandId} · ${item.commandAvailable ? "registered" : "not registered"}` : "No chat command"}</small>{item.usageNote && <span>{item.usageNote}</span>}<div className="button-row"><button className="ghost-button" aria-label={`Edit manual agent ${item.displayName}`} onClick={() => { setEditingAgentId(item.id); setAgentForm({ displayName: item.displayName, chatCommandId: item.chatCommandId ?? "", usageNote: item.usageNote ?? "" }); setShowAgentForm(true); }}>Edit</button><button className="ghost-button" aria-label={`Delete manual agent ${item.displayName}`} disabled={busy} onClick={() => void run(() => bridge.request("executionConfiguration.deleteManualAgent", { correlationId: crypto.randomUUID(), ...ids, agentId: item.id }), "Manual agent deleted.")}>Delete</button></div></div>)}</div>}
      {showAgentForm && <div className="manual-agent-form"><label className="field-stack"><strong>Display name</strong><input aria-label="Manual agent display name" value={agentForm.displayName} onChange={(event) => setAgentForm((value) => ({ ...value, displayName: event.target.value }))} /></label><label className="field-stack"><strong>Optional command ID</strong><input aria-label="Manual agent command ID" value={agentForm.chatCommandId} onChange={(event) => setAgentForm((value) => ({ ...value, chatCommandId: event.target.value }))} /></label><label className="field-stack"><strong>Usage note</strong><input aria-label="Manual agent usage note" value={agentForm.usageNote} onChange={(event) => setAgentForm((value) => ({ ...value, usageNote: event.target.value }))} /></label><div className="button-row"><button className="primary-button" disabled={!agentForm.displayName.trim() || busy} onClick={() => void run(() => editingAgentId ? bridge.request("executionConfiguration.updateManualAgent", { correlationId: crypto.randomUUID(), ...ids, agentId: editingAgentId, displayName: agentForm.displayName, ...(agentForm.chatCommandId.trim() ? { chatCommandId: agentForm.chatCommandId.trim() } : {}), ...(agentForm.usageNote.trim() ? { usageNote: agentForm.usageNote.trim() } : {}) }) : bridge.request("executionConfiguration.createManualAgent", { correlationId: crypto.randomUUID(), ...ids, displayName: agentForm.displayName, ...(agentForm.chatCommandId.trim() ? { chatCommandId: agentForm.chatCommandId.trim() } : {}), ...(agentForm.usageNote.trim() ? { usageNote: agentForm.usageNote.trim() } : {}) }), "Manual agent saved.").then(() => { setEditingAgentId(undefined); setAgentForm({ displayName: "", chatCommandId: "", usageNote: "" }); setShowAgentForm(false); })}>{editingAgentId ? "Update Manual Agent" : "Save Manual Agent"}</button><button className="ghost-button" onClick={() => { setEditingAgentId(undefined); setAgentForm({ displayName: "", chatCommandId: "", usageNote: "" }); setShowAgentForm(false); }}>Cancel</button></div></div>}
    </div>
    <div className="configuration-block"><h3>Development skill</h3>{state.skills.length ? <><label className="field-stack"><strong>Existing skill</strong><select aria-label="Development skill" value={skill} onChange={(event) => { setSkill(event.target.value); setSkillPreview(undefined); }}><option value="">Select a skill</option>{state.skills.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{selectedSkill && <div className="configuration-choice"><strong>{selectedSkill.name}</strong><small>{selectedSkill.source} · v{selectedSkill.version} · {selectedSkill.contentHash.slice(0, 12)}…</small><span>{selectedSkill.description}</span><button className="ghost-button" onClick={() => void bridge.request("executionConfiguration.previewSkill", { correlationId: crypto.randomUUID(), ...ids, skillId: selectedSkill.id }).then(setSkillPreview).catch((cause) => setError(String(cause)))}>Preview skill</button></div>}</> : <p className="bounded-empty">No Development skill is available. Configuration cannot be saved.</p>}{skillPreview && <pre className="instruction-preview">{skillPreview.promptFragment}</pre>}</div>
    <div className="configuration-block"><div className="configuration-title-row"><h3>Instructions</h3><div className="button-row"><button className="ghost-button" onClick={() => void run(() => bridge.request("executionConfiguration.addInstructionFile", { correlationId: crypto.randomUUID(), ...ids }))}>Add instruction file</button><button className="ghost-button" onClick={() => { setPreview(undefined); void run(() => bridge.request("executionConfiguration.refresh", { correlationId: crypto.randomUUID(), ...ids })); }}>Refresh</button></div></div>
      {state.instructions.length ? <ul className="instruction-list">{state.instructions.map((item) => <li key={item.id} className={item.availability !== "available" ? "unavailable" : undefined}><label><input type="checkbox" aria-label={`Instruction ${item.workspaceRelativePath}`} checked={instructions.includes(item.id)} disabled={item.availability !== "available"} onChange={(event) => { const next = event.target.checked ? [...new Set([...instructions, item.id])] : instructions.filter((id) => id !== item.id); setInstructions(next); checkConflicts(next); }} /><strong>{item.name}</strong></label><span>{item.workspaceRelativePath}</span><small>{item.sourceType} · {item.availability} · {item.sizeBytes} bytes{item.contentHash ? ` · ${item.contentHash.slice(0, 12)}…` : ""}</small>{item.diagnostic && <span className="field-error">{item.diagnostic.message}</span>}<button className="ghost-button" aria-label={`Preview ${item.name}`} disabled={item.availability !== "available"} onClick={() => void bridge.request("executionConfiguration.previewInstruction", { correlationId: crypto.randomUUID(), ...ids, instructionId: item.id }).then(setPreview).catch((cause) => setError(String(cause)))}>Preview</button></li>)}</ul> : <p className="bounded-empty">No instruction files were discovered. Add an existing Markdown or text file.</p>}
      {preview && <div className="instruction-preview-panel"><div><strong>{preview.name}</strong><span>{preview.workspaceRelativePath}</span><small>SHA-256 {preview.contentHash} · {preview.sizeBytes} bytes{preview.modifiedAt ? ` · ${new Date(preview.modifiedAt).toLocaleString()}` : ""}</small></div><pre className="instruction-preview">{preview.content}</pre></div>}
    </div>
    {state.conflicts.length > 0 && <div className="configuration-block conflict-block"><h3>Instruction conflicts</h3>{state.conflicts.map((item) => <div key={item.id} className={`conflict-warning ${item.severity}`}><strong>{item.category} · {item.state} · {item.confidence}</strong><span>{item.sourcePaths.join(" ↔ ")}</span><ul>{item.evidence.map((evidence) => <li key={evidence}>{evidence}</li>)}</ul><p>{item.recommendedResolution}</p></div>)}</div>}
    <div className="configuration-block validation-block"><h3>Validation</h3><ul><li>Capability: {selectedMode?.availability ?? "select a mode"}</li><li>Skill: {skill ? "selected" : "required"}</li><li>Instructions: {selectionUnavailable ? "unavailable selection" : `${instructions.length} selected`}</li><li>Conflicts: {blockingConflict ? "blocking conflict" : "resolved"}</li></ul>{state.profile?.status === "stale" && <p className="field-error">Saved configuration is stale. Refresh changed inputs and save again before preparing a prompt.</p>}<div className="button-row"><button className="primary-button" disabled={!valid || !dirty || busy} onClick={() => void run(async () => { const next = await bridge.request("executionConfiguration.saveProfile", { correlationId: crypto.randomUUID(), ...ids, executionCapabilityId: mode, ...(agent ? { agentConfigurationId: agent } : {}), skillId: skill, instructionIds: instructions }); onProfileChange(); return next; }, "Execution configuration saved.")}>Save Configuration</button><button className="ghost-button" disabled={!dirty || busy} onClick={reset}>Reset Unsaved Changes</button></div></div>
  </section>;
}
