import { useCallback, useEffect, useState } from "react";
import type { CanonicalWorkflow } from "../../../shared/contracts/canonicalWorkflow";
import type { ImpactQaAggregate } from "../../../shared/contracts/impactQa";
import type { HostBridge } from "../../services/HostBridge";
import { IntelligenceCanvasWorkspace } from "../intelligence/IntelligenceCanvasWorkspace";

type LooseRequest = (type: string, payload: unknown) => Promise<unknown>;
export function ImpactAnalysisStage({ bridge, workflowId, onWorkflowChange }: { bridge: HostBridge; workflowId: string; onWorkflowChange: (workflow: CanonicalWorkflow) => void }): React.JSX.Element {
  const request = bridge.request.bind(bridge) as LooseRequest; const [state, setState] = useState<ImpactQaAggregate>({ workflowId, changedEntities: [], capabilities: [] }); const [busy, setBusy] = useState<string>(); const [error, setError] = useState<string>();
  const load = useCallback(() => { void request("impact.load", { correlationId: crypto.randomUUID(), workflowId }).then((value) => value && setState(value as ImpactQaAggregate)).catch(report(setError)); }, [request, workflowId]);
  useEffect(load, [load]);
  const act = (name: string, type: string, payload: Record<string, unknown> = {}): void => { setBusy(name); setError(undefined); void request(type, { correlationId: crypto.randomUUID(), workflowId, ...payload }).then((value) => value && setState(value as ImpactQaAggregate)).catch(report(setError)).finally(() => setBusy(undefined)); };
  const acceptImpact = (): void => { if (!state.impactAnalysis) return; setBusy("accept"); void request("impact.acceptAnalysis", { correlationId: crypto.randomUUID(), workflowId, impactAnalysisId: state.impactAnalysis.id, expectedHash: state.impactAnalysis.contentHash }).then((value) => { if (value) setState(value as ImpactQaAggregate); return request("workflow.getCanonical", { workflowId }); }).then((workflow) => workflow && onWorkflowChange(workflow as CanonicalWorkflow)).catch(report(setError)).finally(() => setBusy(undefined)); };
  return <section className="phase7-stage impact-analysis-stage" aria-labelledby="impact-analysis-title"><header><span className="eyebrow">Evidence-backed change review</span><h2 id="impact-analysis-title">Impact Analysis</h2><p>Detect and accept a bounded change-set snapshot before repository traversal.</p></header>
    <div className="button-row"><button className="primary-button" disabled={Boolean(busy)} onClick={() => act("detect", "impact.detect", { manualSelection: false })}>Detect Workspace Changes</button><button disabled={Boolean(busy)} onClick={() => act("manual", "impact.detect", { manualSelection: true })}>Select Changed Files Manually</button><button onClick={load}>Reload persisted analysis</button></div>
    {error && <div role="alert" className="diagnostic error">{error}</div>}{state.detectionMessage && <div role="status" className="canvas-notice">{state.detectionMessage}</div>}
    <section><h3>Change Set</h3>{state.changeSet ? <><p><strong>Source:</strong> {state.changeSet.source} · <strong>Status:</strong> {state.changeSet.status}</p>{state.changeSet.baseRevision && <p>Base: {state.changeSet.baseRevision} · Head: {state.changeSet.headRevision ?? "working tree"}</p>}<ul className="review-list">{state.changeSet.files.map((file) => <li key={file.path}><strong>{file.path}</strong><span>{file.changeType} · {file.staged ? "staged" : "unstaged or unavailable"}</span><button onClick={() => act("open", "impact.openChangedFile", { path: file.path })}>Open file</button></li>)}</ul><button disabled={Boolean(busy)} onClick={() => act("accept-change", "impact.acceptChangeSet", { expectedHash: state.changeSet!.contentHash })}>Accept Change Set Snapshot</button></> : <p>No accepted workspace-change snapshot yet.</p>}</section>
    <section><h3>Changed Symbols</h3>{state.changedEntities.length ? <ul>{state.changedEntities.map((item) => <li key={item.id}>{item.entityId ?? "File-level fallback"} · {item.filePath} · {item.changeType} · {item.confidence.toFixed(2)}</li>)}</ul> : <p>Accept a change set to resolve changed symbols.</p>}<button disabled={!state.changeSet || !state.changedEntities.length || Boolean(busy)} onClick={() => act("analyze", "impact.analyze", { expectedHash: state.changeSet!.contentHash })}>Analyze Bounded Impact</button></section>
    {state.impactAnalysis && <><section><h3>Risk</h3><strong className={`risk-${state.impactAnalysis.risk.level}`}>{state.impactAnalysis.risk.level.toUpperCase()}</strong><ul>{state.impactAnalysis.risk.factors.map((factor) => <li key={factor.id}>{factor.description}</li>)}</ul></section><section><h3>Impact Graph</h3><p>{state.impactAnalysis.summary}</p><IntelligenceCanvasWorkspace bridge={bridge} intelligenceRevision={state.impactAnalysis.intelligenceRevision} initialGraph={state.impactAnalysis.graph} embedded /></section><section className="impact-columns"><div><h3>Affected Flows</h3>{state.impactAnalysis.affectedFlowIds.length ? <ul>{state.impactAnalysis.affectedFlowIds.map((id) => <li key={id}>{state.impactAnalysis!.impacts.find((item) => item.entityId === id)?.label ?? id}</li>)}</ul> : <p>No evidence-backed affected entry-point flows.</p>}</div><div><h3>Contracts</h3>{state.impactAnalysis.affectedContractIds.length ? <ul>{state.impactAnalysis.affectedContractIds.map((id) => <li key={id}>{state.impactAnalysis!.graph.nodes.find((node) => node.id === id)?.label ?? id}</li>)}</ul> : <p>No supported public-contract impact found.</p>}</div></section><section className="impact-columns"><div><h3>Related Tests</h3><ul>{state.impactAnalysis.mappedTests.map((mapping) => <li key={mapping.id}>{mapping.testFilePath} · {mapping.mappingType} · {mapping.confidence.toFixed(2)}</li>)}</ul></div><div><h3>Coverage Gaps</h3>{state.impactAnalysis.coverageGaps.length ? <ul>{state.impactAnalysis.coverageGaps.map((gap) => <li key={gap.id}>{gap.blocking ? "Blocking" : "Warning"}: {gap.reason} · recommend {gap.recommendedTestLayer}</li>)}</ul> : <p>No mapped coverage gaps.</p>}</div></section><section><h3>Review and Accept</h3><p>Review changed roots, evidence-backed paths, coverage gaps, and named risk factors before advancing.</p><button className="primary-button" disabled={state.impactAnalysis.status === "accepted" || Boolean(busy)} onClick={acceptImpact}>{state.impactAnalysis.status === "accepted" ? "Impact Analysis Accepted" : "Accept Impact Analysis and Open QA"}</button></section></>}
  </section>;
}
function report(setter: (value: string) => void) { return (cause: unknown): void => setter(cause instanceof Error ? cause.message : String(cause)); }
