import { useCallback, useEffect, useState } from "react";
import type { CanonicalWorkflow } from "../../../shared/contracts/canonicalWorkflow";
import type { ImpactQaAggregate, QaPlanItem } from "../../../shared/contracts/impactQa";
import type { HostBridge } from "../../services/HostBridge";

type LooseRequest = (type: string, payload: unknown) => Promise<unknown>;
export function QaStage({ bridge, workflowId, onWorkflowChange }: { bridge: HostBridge; workflowId: string; onWorkflowChange: (workflow: CanonicalWorkflow) => void }): React.JSX.Element {
  const request = bridge.request.bind(bridge) as LooseRequest; const [state, setState] = useState<ImpactQaAggregate>({ workflowId, changedEntities: [], capabilities: [] }); const [busy, setBusy] = useState<string>(); const [output, setOutput] = useState(""); const [runningCommandId, setRunningCommandId] = useState<string>(); const [error, setError] = useState<string>();
  const load = useCallback(() => { void request("impact.load", { correlationId: crypto.randomUUID(), workflowId }).then((value) => value && setState(value as ImpactQaAggregate)).catch(report(setError)); }, [request, workflowId]); useEffect(load, [load]);
  useEffect(() => bridge.subscribe((message) => { if (message.type !== "qa.progress") return; if (message.payload.status === "running" && message.payload.commandId) setRunningCommandId(message.payload.commandId); else if (message.payload.status !== "running") setRunningCommandId(undefined); if ("output" in message.payload && typeof message.payload.output === "string") setOutput((value) => `${value}${message.payload.output}`.slice(-50_000)); }), [bridge]);
  const act = (name: string, type: string, payload: Record<string, unknown> = {}): void => { setBusy(name); setError(undefined); void request(type, { correlationId: crypto.randomUUID(), workflowId, ...payload }).then((value) => value && setState(value as ImpactQaAggregate)).then(() => request("workflow.getCanonical", { workflowId })).then((workflow) => workflow && onWorkflowChange(workflow as CanonicalWorkflow)).catch(report(setError)).finally(() => setBusy(undefined)); };
  const groups: Array<{ title: string; items: QaPlanItem[] }> = [{ title: "Required Tests", items: state.qaPlan?.requiredItems ?? [] }, { title: "Recommended Tests", items: state.qaPlan?.recommendedItems ?? [] }, { title: "Optional Regression", items: state.qaPlan?.optionalItems ?? [] }];
  return <section className="phase7-stage qa-stage" aria-labelledby="qa-title"><header><span className="eyebrow">Controlled execution</span><h2 id="qa-title">QA</h2><p>Review exact repository-derived commands, approve once, then observe real execution.</p></header>{error && <div role="alert" className="diagnostic error">{error}</div>}
    <div className="button-row"><button className="primary-button" disabled={Boolean(busy) || !state.impactAnalysis} onClick={() => act("generate", "qa.generatePlan")}>Generate QA Plan</button><button onClick={load}>Reload persisted QA</button></div>
    <section><h3>Plan Summary</h3><p>{state.qaPlan ? `${state.qaPlan.requiredItems.length} required · ${state.qaPlan.recommendedItems.length} recommended · ${state.qaPlan.optionalItems.length} optional` : "No plan generated."}</p></section>
    {groups.map((group) => <section key={group.title}><h3>{group.title}</h3>{group.items.length ? <ul className="qa-plan-list">{group.items.map((item) => <li key={item.id}><label><input type="checkbox" checked={item.selected} onChange={(event) => act("select", "qa.updatePlan", { itemId: item.id, selected: event.target.checked, overrideReason: item.category === "required" && !event.target.checked ? "User explicitly excluded this required test." : undefined })} /> <strong>{item.label}</strong></label><p>{item.reason}</p><small>{item.command.executable} {item.command.arguments.join(" ")} · cwd {item.command.workingDirectory} · timeout {item.command.timeoutMs}ms · confidence {item.confidence.toFixed(2)}</small></li>)}</ul> : <p>No {group.title.toLowerCase()} selected.</p>}</section>)}
    <section><h3>Coverage Gaps</h3>{state.impactAnalysis?.coverageGaps.length ? <ul>{state.impactAnalysis.coverageGaps.map((gap) => <li key={gap.id}>{gap.blocking ? "Blocking" : "Warning"}: {gap.reason}</li>)}</ul> : <p>No known coverage gaps.</p>}</section>
    <section><h3>Command Approval</h3><button className="primary-button" disabled={!state.qaPlan || state.qaPlan.status !== "ready-for-review" || Boolean(busy)} onClick={() => act("approve", "qa.approvePlan", { qaPlanId: state.qaPlan!.id, expectedHash: state.qaPlan!.contentHash })}>Approve Exact Commands</button><button disabled={!state.qaPlan || state.qaPlan.status !== "approved" || Boolean(busy)} onClick={() => act("execute", "qa.execute", { qaPlanId: state.qaPlan!.id })}>Run Approved Tests</button><button disabled={!runningCommandId} onClick={() => { const commandId = runningCommandId; if (!commandId) return; setError(undefined); void request("qa.cancel", { correlationId: crypto.randomUUID(), workflowId, commandId }).catch(report(setError)); }}>Cancel Running Tests</button></section>
    {output && <details open><summary>Live bounded output</summary><pre className="qa-output">{output}</pre></details>}{state.execution && <section><h3>Test Results</h3><p>Status: {state.execution.status} · {state.execution.commandRuns.length} command(s)</p>{state.execution.parsedResults.map((result, index) => <article key={index}><strong>{result.framework} · {result.parseStatus}</strong><p>Tests: {result.tests.passed ?? "?"} passed · {result.tests.failed ?? "?"} failed · {result.tests.skipped ?? "?"} skipped</p></article>)}<details><summary>Raw command output</summary><pre className="qa-output">{state.execution.commandRuns.map((run) => run.rawOutput).join("\n")}</pre></details></section>}{state.decision && <section className={`qa-decision decision-${state.decision.decision}`}><h3>QA Decision</h3><strong>{state.decision.decision}</strong><ul>{state.decision.gates.map((gate) => <li key={gate.id}>{gate.passed ? "Passed" : "Not passed"}: {gate.message}</li>)}</ul></section>}
  </section>;
}
function report(setter: (value: string) => void) { return (cause: unknown): void => setter(cause instanceof Error ? cause.message : String(cause)); }
