import { z } from "zod";
import type { IntelligenceGraphSlice } from "./intelligenceCanvas";

export const ChangedRangeSchema = z.object({ oldStartLine: z.number().int().nonnegative().optional(), oldEndLine: z.number().int().nonnegative().optional(), newStartLine: z.number().int().nonnegative().optional(), newEndLine: z.number().int().nonnegative().optional() }).strict();
export const Phase7ChangedFileSchema = z.object({ path: z.string().min(1).max(2000), changeType: z.enum(["added", "modified", "deleted", "renamed", "unknown"]), oldPath: z.string().max(2000).optional(), staged: z.boolean().optional(), changedRanges: z.array(ChangedRangeSchema).max(500).optional(), source: z.enum(["git", "filesystem", "manual"]) }).strict();
export const Phase7ChangeSetSchema = z.object({ id: z.string().min(1), workflowId: z.string().uuid(), developmentResultId: z.string().optional(), source: z.enum(["git", "workspace-snapshot", "manual-selection"]), baseRevision: z.string().optional(), headRevision: z.string().optional(), files: z.array(Phase7ChangedFileSchema).max(5000), status: z.enum(["draft", "ready", "stale", "failed"]), createdAt: z.string().datetime(), updatedAt: z.string().datetime(), contentHash: z.string().startsWith("sha256:") }).strict();
export type Phase7ChangedFile = z.infer<typeof Phase7ChangedFileSchema>;
export type Phase7ChangeSet = z.infer<typeof Phase7ChangeSetSchema>;

export const Phase7ChangedEntitySchema = z.object({ id: z.string(), entityId: z.string().optional(), filePath: z.string(), changeType: z.enum(["added", "modified", "removed", "signature-changed", "file-level"]), range: z.object({ startLine: z.number().int().nonnegative(), endLine: z.number().int().nonnegative() }).optional(), confidence: z.number().min(0).max(1), evidenceIds: z.array(z.string()), intelligenceRevision: z.string() }).strict();
export type Phase7ChangedEntity = z.infer<typeof Phase7ChangedEntitySchema>;

export interface Phase7ImpactItem { id: string; changedRootId: string; entityId: string; label: string; filePath?: string; category: "direct-caller" | "direct-dependent" | "transitive-dependent" | "affected-flow" | "contract" | "test"; relationshipPath: string[]; distance: number; confidence: number; inferred: boolean; evidenceIds: string[]; reason: string }
export interface Phase7TestMapping { id: string; productionEntityId: string; testEntityId?: string; testFilePath: string; mappingType: "runtime-coverage" | "symbol-reference" | "import" | "call" | "configuration" | "naming-heuristic"; confidence: number; evidenceIds: string[]; distance: number }
export interface Phase7CoverageGap { id: string; entityId?: string; flowId?: string; reason: string; confidence: number; recommendedTestLayer: "unit" | "integration" | "contract" | "e2e"; blocking: boolean }
export interface Phase7ImpactAnalysis { id: string; workflowId: string; changeSetId: string; intelligenceRevision: string; changedEntityIds: string[]; impacts: Phase7ImpactItem[]; affectedFlowIds: string[]; affectedContractIds: string[]; mappedTests: Phase7TestMapping[]; coverageGaps: Phase7CoverageGap[]; graph: IntelligenceGraphSlice; risk: { level: "low" | "medium" | "high"; factors: Array<{ id: string; description: string; evidenceIds: string[] }> }; status: "ready-for-review" | "accepted" | "stale" | "failed"; createdAt: string; contentHash: string; summary: string }

export interface TestCommandDefinition { id: string; frameworkId: string; displayName: string; executable: string; arguments: string[]; workingDirectory: string; scope: "test-case" | "test-file" | "suite" | "repository"; source: "package-script" | "configuration" | "user-configured"; timeoutMs: number }
export interface TestFrameworkCapability { id: string; framework: string; sourceFiles: string[]; commands: TestCommandDefinition[]; availability: "available" | "partial" | "unsupported"; diagnostic?: { code: string; message: string } }
export interface QaPlanItem { id: string; testFilePath?: string; label: string; layer: string; command: TestCommandDefinition; reason: string; affectedEntityIds: string[]; confidence: number; category: "required" | "recommended" | "optional"; selected: boolean; overrideReason?: string }
export interface Phase7QaPlan { id: string; workflowId: string; impactAnalysisId: string; impactHash: string; changeSetHash: string; requiredItems: QaPlanItem[]; recommendedItems: QaPlanItem[]; optionalItems: QaPlanItem[]; coverageGapIds: string[]; status: "draft" | "ready-for-review" | "approved" | "executing" | "completed" | "stale"; createdAt: string; contentHash: string }
export interface NormalizedTestResult { framework: string; suites: { total?: number; passed?: number; failed?: number; skipped?: number }; tests: { total?: number; passed?: number; failed?: number; skipped?: number }; failures: Array<{ name?: string; message: string; stackFrames: string[] }>; durationMs?: number; parseStatus: "parsed" | "partially-parsed" | "unparsed" }
export interface QaCommandResult { id: string; commandDefinitionId: string; status: "completed" | "failed" | "cancelled" | "timed-out" | "command-start-failed"; startedAt: string; completedAt: string; exitCode?: number; signal?: string; cancelled: boolean; timedOut: boolean; rawOutput: string; durationMs: number }
export interface Phase7QaDecision { id: string; workflowId: string; qaPlanId: string; qaExecutionId?: string; decision: "passed" | "passed-with-warnings" | "failed" | "incomplete" | "cancelled"; gates: Array<{ id: string; passed: boolean; evidenceIds: string[]; message: string }>; unresolvedFailureIds: string[]; coverageGapIds: string[]; createdAt: string; contentHash: string }
export interface Phase7QaExecution { id: string; workflowId: string; qaPlanId: string; commandRuns: QaCommandResult[]; parsedResults: NormalizedTestResult[]; status: "queued" | "running" | "cancelled" | "completed" | "failed" | "interrupted"; startedAt?: string; completedAt?: string }
export interface ImpactQaAggregate { workflowId: string; changeSet?: Phase7ChangeSet; changedEntities: Phase7ChangedEntity[]; impactAnalysis?: Phase7ImpactAnalysis; capabilities: TestFrameworkCapability[]; qaPlan?: Phase7QaPlan; execution?: Phase7QaExecution; decision?: Phase7QaDecision; detectionMessage?: string }
