import { useEffect, useState } from "react";
import type { BootstrapSnapshot, AppRoute } from "../../../shared/contracts/domain";
import type { CopilotCapabilities, DevelopmentWorkflowSnapshot } from "../../../shared/contracts/delegation";
import type { WorkflowInstance } from "../../../shared/contracts/orchestration";
import { workbenchRoute } from "../../../shared/navigation";
import type { HostBridge } from "../../services/HostBridge";
import { Icon } from "../Icon";

export function HomeDashboard({ bootstrap, bridge, navigate }: { bootstrap: BootstrapSnapshot; bridge: HostBridge; navigate: (route: AppRoute) => void }): React.JSX.Element {
  const [workflows, setWorkflows] = useState<DevelopmentWorkflowSnapshot[]>([]); const [instances, setInstances] = useState<WorkflowInstance[]>([]); const [copilot, setCopilot] = useState<CopilotCapabilities>(); const [notice, setNotice] = useState<string>();
  useEffect(() => { let active = true; void Promise.all([bridge.request("workflow/list", {}), bridge.request("orchestration/list", {}), bridge.request("copilot/capabilities", {})]).then(([flows, orchestration, capabilities]) => { if (active) { setWorkflows(Array.isArray(flows) ? flows : []); setInstances(Array.isArray(orchestration) ? orchestration : []); if (capabilities) setCopilot(capabilities); } }).catch((cause: unknown) => { if (active) setNotice(cause instanceof Error ? cause.message : String(cause)); }); return () => { active = false; }; }, [bridge]);
  const workflow = workflows.find((item) => !["completed", "cancelled"].includes(item.status)) ?? workflows.at(-1); const instance = instances.find((item) => item.intentId === workflow?.intent.id) ?? instances.at(-1); const task = workflow?.tasks.find((item) => ["executing", "ready", "blocked"].includes(item.status)) ?? workflow?.tasks[0];
  const resume: AppRoute = workflow ? workbenchRoute(workflow.id, workflow.tasks.length ? task?.status === "completed" ? "validate" : "build" : workflow.specification?.status === "approved" ? "plan" : "define") : "/workbench/new";
  const importHandoff = async (): Promise<void> => { try { const imported = await bridge.request("handoff/import", { source: "file" }); setNotice(imported ? `Imported ${imported.package.task.title} for review.` : "Handoff import cancelled."); } catch (cause) { setNotice(cause instanceof Error ? cause.message : String(cause)); } };
  return <section className="page home-page"><div className="hero"><div className="eyebrow"><Icon name="repo" size={14}/> Active repository · {bootstrap.workspace.name}</div><h1>Engineering work,<br/><em>in one lifecycle.</em></h1><p>Start from an intent, define the contract, plan tasks, build, validate, review, and complete only the capabilities this workflow needs.</p><div className="button-row"><button className="primary-button" onClick={() => navigate("/workbench/new")}>Start new work</button>{workflow && <button className="ghost-button" onClick={() => navigate(resume)}>Resume workflow</button>}<button className="ghost-button" onClick={() => navigate("/intelligence")}>Ask repository</button><button className="ghost-button" onClick={() => void importHandoff()}>Import handoff</button></div></div>{notice && <div role="status" className="honesty-note">{notice}</div>}<div className="status-grid"><Projection label="INTELLIGENCE" value={bootstrap.workspace.indexStatus.replace("-", " ")} detail="Active local repository model"/><Projection label="ACTIVE WORKFLOW" value={workflow?.specification?.title ?? workflow?.intent.normalizedObjective ?? "None"} detail={workflow?.status ?? "Start new work"}/><Projection label="CURRENT TASK" value={task?.title ?? "None"} detail={task?.status ?? "No task is active"}/><Projection label="PENDING APPROVAL" value={String(instance?.progress.pendingApprovals ?? 0)} detail="Workflow approval gates"/><Projection label="BLOCKING FINDINGS" value={String(instance?.progress.blockingFindings ?? 0)} detail="Open blocking review findings"/><Projection label="VALIDATION" value={instance?.currentStage?.includes("validation") ? instance.currentStage : "Not active"} detail="Current workflow validation state"/><Projection label="COPILOT" value={copilot?.extensionDetected ? "Available" : "Unavailable"} detail={copilot?.directInvocationAvailable ? "Direct invocation supported" : "Capability-driven fallback required"}/></div></section>;
}
function Projection({ label, value, detail }: { label: string; value: string; detail: string }): React.JSX.Element { return <article className="status-card"><small>{label}</small><h2>{value}</h2><p>{detail}</p></article>; }
