import { useEffect, useMemo, useRef, useState } from "react";
import type { IntelligenceQueryResult, QueryCompilation, QuerySuggestionsResult, QueryTemplatesResult } from "../../../shared/contracts/query";
import type { HostBridge } from "../../services/HostBridge";

const HISTORY_KEY = "keystone.intelligence.queryHistory.v1";

export function QueryWorkspace({ bridge }: { bridge: HostBridge }): React.JSX.Element {
  const [input, setInput] = useState(""); const [compilation, setCompilation] = useState<QueryCompilation>(); const [suggestions, setSuggestions] = useState<QuerySuggestionsResult["items"]>([]); const [templates, setTemplates] = useState<QueryTemplatesResult["templates"]>([]); const [result, setResult] = useState<IntelligenceQueryResult>(); const [loading, setLoading] = useState(false); const [error, setError] = useState<string>(); const [history, setHistory] = useState<string[]>(readHistory); const controller = useRef<AbortController | undefined>(undefined);
  useEffect(() => { void bridge.request("intelligence/query/templates", {}).then((value) => setTemplates(value.templates)).catch(report(setError)); }, [bridge]);
  useEffect(() => { if (!input.trim()) return undefined; const timer = window.setTimeout(() => { void bridge.request("intelligence/query/suggestions", { input, limit: 8 }).then((value) => setSuggestions(value.items)).catch(() => undefined); }, 120); return () => window.clearTimeout(timer); }, [bridge, input]);
  const grouped = useMemo(() => result ? Object.entries(result.data.sections).filter(([, items]) => items.length) : [], [result]);
  const compile = async (): Promise<QueryCompilation | undefined> => { if (!input.trim()) return undefined; setError(undefined); try { const value = await bridge.request("intelligence/query/compile", { text: input }); setCompilation(value); return value; } catch (cause) { report(setError)(cause); return undefined; } };
  const run = async (): Promise<void> => { const compiled = await compile(); if (!compiled?.parsed) return; controller.current?.abort(); const next = new AbortController(); controller.current = next; setLoading(true); try { const value = await bridge.request("intelligence/query", { text: input }, { signal: next.signal }); setResult(value); const values = [input, ...history.filter((item) => item !== input)].slice(0, 12); setHistory(values); localStorage.setItem(HISTORY_KEY, JSON.stringify(values)); } catch (cause) { if (!(cause instanceof DOMException && cause.name === "AbortError")) report(setError)(cause); } finally { setLoading(false); } };
  const cancel = (): void => { controller.current?.abort(); setLoading(false); };

  return <section className="query-workspace" aria-label="Intelligence query workspace">
    <header><div><small>Deterministic Query Workspace</small><h2>Ask Keystone intelligence</h2></div><span>No LLM · local generation only</span></header>
    <div className="query-input-row"><input aria-label="Global intelligence query" value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void run(); }} placeholder="Path from POST /orders to orders.status"/><button className="ghost-button" onClick={() => void compile()}>Compile</button>{loading ? <button className="danger-button" onClick={cancel}>Cancel</button> : <button className="primary-button" onClick={() => void run()}>Run query</button>}</div>
    {suggestions.length > 0 && <div className="query-suggestions" role="listbox" aria-label="Deterministic autocomplete">{suggestions.map((item) => <button key={`${item.kind}:${item.entityId ?? item.value}`} onClick={() => setInput(item.value)}><strong>{item.label}</strong><small>{item.kind} · {item.detail}</small></button>)}</div>}
    <div className="query-helpers"><details><summary>Supported templates</summary>{templates.map((item) => <button key={item.id} onClick={() => setInput(item.template)}>{item.template}</button>)}</details>{history.length > 0 && <details><summary>Recent queries</summary>{history.map((item) => <button key={item} onClick={() => setInput(item)}>{item}</button>)}</details>}</div>
    {error && <p className="semantic-error" role="alert">{error}</p>}
    {compilation && <section className="compiled-query"><div><strong>Parsed intent</strong><span>{compilation.parsed ? `${compilation.query?.operation} · ${compilation.rule}` : "Unsupported"}</span></div>{compilation.query && <pre>{JSON.stringify(compilation.query, null, 2)}</pre>}{compilation.diagnostics.map((item) => <p key={item.code}>{item.message}</p>)}</section>}
    {result && <section className="query-result" aria-label="Query result"><header><div><small>{result.operation}</small><h3>{result.data.kind}</h3></div><span>{result.executionTimeMs.toFixed(1)} ms · generation {result.generation} · cache {result.cacheState}</span></header>
      {result.resolvedSeeds.map((seed, index) => <div className="resolved-seed" key={index}><strong>{seed.selected?.qualifiedName ?? "Explicit selection required"}</strong><span>{seed.ambiguous ? `${seed.candidates.length} ranked candidates` : seed.reasons.join(" · ")}</span></div>)}
      {result.diagnostics.map((item) => <p className={`query-diagnostic ${item.severity}`} key={`${item.code}:${item.message}`}>{item.code}: {item.message}</p>)}
      {result.data.items.length > 0 && <div className="query-items">{result.data.items.map((item) => <article key={`${item.group ?? "item"}:${item.id}`}><div><strong>{item.name}</strong><span>{item.group ?? item.classification} · {Math.round(item.confidence * 100)}%</span></div><small>{item.qualifiedName}<br/>{item.rankingReasons.slice(0, 3).join(" · ")}</small>{item.details?.riskFactors && <p>{(item.details.riskFactors as string[]).join(" · ")}</p>}</article>)}</div>}
      {result.data.paths.map((path, index) => <div className="query-path" key={index}><strong>Path {index + 1} · confidence {Math.round(path.confidence * 100)}% · risk {path.risk}</strong><ol>{path.steps.map((step, stepIndex) => <li key={`${step.entityId}:${stepIndex}`}><span>{step.entityName}</span>{step.relationshipType && <small>{step.relationshipType.replace("keystone.core.", "")} · {step.classification}</small>}</li>)}</ol>{path.unsupportedBoundaries.length > 0 && <p>{path.unsupportedBoundaries.join(" · ")}</p>}</div>)}
      {grouped.length > 0 && <div className="query-sections">{grouped.map(([name, items]) => <div key={name}><strong>{name}</strong><span>{items.length}</span></div>)}</div>}
      {result.data.cpg && <p className="query-cpg">CPG result: {result.data.cpg.nodes.length} nodes · {result.data.cpg.edges.length} edges{result.data.cpg.truncated ? " · truncated" : ""}</p>}
      <details className="query-explanation"><summary>Explain this query</summary><p>{result.explanation.steps.join(" ")}</p><dl><dt>Indexes</dt><dd>{result.explanation.indexesUsed.join(", ") || "entity indexes"}</dd><dt>Relationships</dt><dd>{result.explanation.relationshipFamilies.join(", ") || "none"}</dd><dt>Confidence</dt><dd>{result.explanation.confidenceThreshold}</dd><dt>Ranking</dt><dd>{result.explanation.rankingRules.join(" · ")}</dd><dt>Boundaries</dt><dd>{result.explanation.capabilityBoundaries.join(" · ") || "none"}</dd></dl>{result.evidence.map((item) => <div key={item.id}><strong>{item.extractorId}@{item.extractorVersion}</strong><span>{item.statement}</span><small>{item.relativePath} · {Math.round(item.confidence * 100)}%</small></div>)}</details>
    </section>}
  </section>;
}

function readHistory(): string[] { try { const value = JSON.parse(localStorage.getItem(HISTORY_KEY) ?? "[]") as unknown; return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string").slice(0, 12) : []; } catch { return []; } }
function report(setError: (value: string) => void): (cause: unknown) => void { return (cause) => setError(cause instanceof Error ? cause.message : String(cause)); }
