import { useEffect, useMemo, useState } from "react";
import type { HostBridge } from "../../services/HostBridge";
import type { AgentRecommendation, CopilotAgentDescriptor, CopilotCapabilities, DelegationSession, DevelopmentWorkflowSnapshot, PreparedDelegation, TaskContextPackage } from "../../../shared/contracts/delegation";
import type { TaskExecutionSession } from "../../../shared/contracts/execution";

export function DevelopmentWorkspace({ bridge, section, workflowId: requestedWorkflowId }: { bridge: HostBridge; section: "intent" | "specifications" | "tasks" | "context"; workflowId?: string }): React.JSX.Element {
  const [workflows, setWorkflows] = useState<DevelopmentWorkflowSnapshot[]>([]); const [workflowId, setWorkflowId] = useState<string>();
  const [text, setText] = useState(""); const [mode, setMode] = useState<"quick" | "guided" | "spec-driven">("spec-driven"); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>();
  const [capabilities, setCapabilities] = useState<CopilotCapabilities>(); const [agents, setAgents] = useState<CopilotAgentDescriptor[]>([]); const [context, setContext] = useState<TaskContextPackage>(); const [prepared, setPrepared] = useState<PreparedDelegation>(); const [session, setSession] = useState<DelegationSession>();
  const [recommendation, setRecommendation] = useState<AgentRecommendation>();
  const [execution, setExecution] = useState<TaskExecutionSession>();
  const workflow = useMemo(() => workflows.find((item) => item.id === workflowId) ?? workflows.at(-1), [workflowId, workflows]); const specification = workflow?.specification; const task = workflow?.tasks.find((item) => item.status === "ready") ?? workflow?.tasks[0]; const taskId = task?.id;

  useEffect(() => { void Promise.all([bridge.request("workflow/list", {}), bridge.request("copilot/capabilities", {}), bridge.request("copilot/agents", {})]).then(([items, detected, available]) => { setWorkflows((current) => current.length ? current : items); setWorkflowId((current) => requestedWorkflowId ?? current ?? items.at(-1)?.id); setCapabilities(detected); setAgents(available); }).catch(show(setError)); }, [bridge, requestedWorkflowId]);
  useEffect(() => { if (!taskId) return; void Promise.all([bridge.request("context/get", { taskId }), bridge.request("delegation/getPrompt", { taskId })]).then(([value, prompt]) => { setContext(value); setPrepared(prompt); }).catch(() => undefined); }, [bridge, taskId]);
  useEffect(() => { if (!taskId || !workflow?.id || !agents.length) return; void bridge.request("copilot/agentRecommendation", { workflowId: workflow.id, taskId, selectionMode: "recommended" }).then(setRecommendation).catch(() => undefined); }, [agents.length, bridge, taskId, workflow?.id]);

  const run = async <T,>(operation: () => Promise<T>, apply: (value: T) => void): Promise<void> => { setBusy(true); setError(undefined); try { apply(await operation()); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } };
  const updateWorkflow = (value: DevelopmentWorkflowSnapshot): void => { setWorkflows((current) => [...current.filter((item) => item.id !== value.id), value]); setWorkflowId(value.id); };

  if (section === "intent") return <section className="page delegation-page"><Heading eyebrow="Repository-aware development" title="Intent capture" description="Choose a workflow mode. Keystone resolves explicit files and symbols through canonical Intelligence; it does not ask Copilot or invent agents."/>{error && <ErrorText value={error}/>}<div className="workflow-form"><textarea aria-label="Development intent" value={text} onChange={(event) => setText(event.target.value)} placeholder="Describe the approved repository change…" maxLength={50_000}/><div className="button-row"><select aria-label="Development mode" value={mode} onChange={(event) => setMode(event.target.value as typeof mode)}><option value="quick">Quick</option><option value="guided">Guided</option><option value="spec-driven">Spec-driven</option></select><button disabled={busy || !text.trim()} className="primary-button" onClick={() => void run(() => bridge.request("workflow/capture", { text, mode }), updateWorkflow)}>Capture intent</button></div></div><WorkflowPicker workflows={workflows} value={workflow?.id} onChange={setWorkflowId}/>{workflow && <IntentSummary workflow={workflow}/>}</section>;

  if (section === "specifications") return <section className="page delegation-page"><Heading eyebrow="Approve before delegation" title="Define" description="Clarify the durable intent, then review deterministic scope, requirements, constraints, criteria, test strategy, risks, decisions, and evidence."/>{error && <ErrorText value={error}/>}<WorkflowPicker workflows={workflows} value={workflow?.id} onChange={setWorkflowId}/>{workflow && specification ? <><IntentSummary workflow={workflow}/><SpecSummary workflow={workflow}/><SpecificationControls workflow={workflow} busy={busy} act={(operation) => void run(operation, updateWorkflow)} bridge={bridge}/></> : <Empty value="Capture intent to create a specification."/>}</section>;

  if (section === "tasks") return <section className="page delegation-page"><Heading eyebrow="Dependency-ordered work" title="Task readiness and agents" description="Only approved, current tasks with satisfied dependencies, criteria, validation, context, and a confirmed agent can be delegated."/>{error && <ErrorText value={error}/>}<WorkflowPicker workflows={workflows} value={workflow?.id} onChange={setWorkflowId}/>{workflow ? <><TaskList workflow={workflow}/>{task && <div className="delegation-panel"><h3>Agent selection</h3><CapabilitySummary capabilities={capabilities}/><div className="agent-grid">{agents.map((agent) => { const ranked = recommendation?.candidates.find((item) => item.agent.id === agent.id); return <button key={agent.id} disabled={agent.availability === "unavailable" || busy} className={task.assignedAgentId === agent.id ? "agent-card selected" : "agent-card"} onClick={() => void run(() => bridge.request("copilot/selectAgent", { workflowId: workflow.id, taskId: task.id, agentId: agent.id, confirmed: true }), updateWorkflow)}><strong>{ranked ? `#${ranked.rank} · ` : ""}{agent.displayName}</strong><span>{agent.availability} · {agent.source}</span><small>{agent.capabilities.join(", ") || "No configured capabilities"}</small>{ranked && <small>{ranked.reasons.join(" · ")}</small>}</button>; })}</div><div className="button-row"><button onClick={() => void run(() => bridge.request("copilot/refreshCapabilities", {}), setCapabilities)}>Refresh capabilities</button><button onClick={() => void run(() => bridge.request("copilot/refreshAgents", {}), setAgents)}>Refresh agents</button><button disabled={!task.assignedAgentId || busy} className="primary-button" onClick={() => void run(() => bridge.request("context/build", { workflowId: workflow.id, taskId: task.id }), setContext)}>Build context</button></div></div>}</> : <Empty value="No active workflow."/>}</section>;

  return <section className="page delegation-page"><Heading eyebrow="Exact payload review" title="Context and controlled delegation" description="Inspect every included and removed item, approve the fingerprints, then use a capability-driven direct, assisted, or clipboard path."/>{error && <ErrorText value={error}/>}<WorkflowPicker workflows={workflows} value={workflow?.id} onChange={setWorkflowId}/>{workflow && task ? <><ContextPanel context={context} busy={busy} onPin={(id, pinned) => void run(() => bridge.request(pinned ? "context/pinItem" : "context/unpinItem", { taskId: task.id, itemId: id }), setContext)} onRemove={(id) => void run(() => bridge.request("context/removeItem", { taskId: task.id, itemId: id }), setContext)} onRestore={(id) => void run(() => bridge.request("context/update", { taskId: task.id, itemId: id }), setContext)}/><div className="button-row">{context && <button disabled={busy || context.reviewed} onClick={() => void run(() => bridge.request("context/validate", { taskId: task.id, contentFingerprint: context.contentFingerprint }), setContext)}>Approve context</button>}<button disabled={busy || !context?.reviewed || !task.assignedAgentId} onClick={() => void run(() => bridge.request("delegation/prepare", { workflowId: workflow.id, taskId: task.id }), setPrepared)}>Prepare prompt</button></div>{prepared && <PromptPanel prepared={prepared} session={session} execution={execution} busy={busy} onApprove={() => void run(() => bridge.request("delegation/approve", { taskId: task.id, promptFingerprint: prepared.promptFingerprint, contextFingerprint: prepared.contextFingerprint }), setPrepared)} onCopy={() => void run(() => bridge.request("delegation/copyPrompt", { taskId: task.id }), () => undefined)} onStart={() => void run(() => bridge.request("delegation/start", { workflowId: workflow.id, taskId: task.id, overlapOverride: false }), setSession)} onTrack={() => session && void run(() => bridge.request("execution/start", { workflowId: workflow.id, taskId: task.id, delegationSessionId: session.id }), setExecution)} onConfirmStarted={() => session && void run(() => bridge.request("delegation/confirmStarted", { workflowId: workflow.id, sessionId: session.id }), setSession)} onConfirmStopped={() => session && void run(() => bridge.request("delegation/confirmStopped", { workflowId: workflow.id, sessionId: session.id }), setSession)} onCancel={() => session && void run(() => bridge.request("delegation/cancel", { workflowId: workflow.id, sessionId: session.id }), setSession)}/>}</> : <Empty value="Generate a ready task and select an agent first."/>}</section>;
}

function Heading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }): React.JSX.Element { return <><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></>; }
function WorkflowPicker({ workflows, value, onChange }: { workflows: DevelopmentWorkflowSnapshot[]; value?: string; onChange: (id: string) => void }): React.JSX.Element { if (!workflows.length) return <></>; return <label className="workflow-picker">Workflow<select value={value} onChange={(event) => onChange(event.target.value)}>{workflows.map((item) => <option key={item.id} value={item.id}>{item.specification?.title ?? item.intent.normalizedObjective} · {item.status}</option>)}</select></label>; }
function IntentSummary({ workflow }: { workflow: DevelopmentWorkflowSnapshot }): React.JSX.Element { return <div className="summary-card"><h2>{workflow.intent.normalizedObjective}</h2><dl><div><dt>Mode</dt><dd>{workflow.intent.mode}</dd></div><div><dt>Risk</dt><dd>{workflow.intent.risk}</dd></div><div><dt>Generation</dt><dd>{workflow.intent.intelligenceGeneration}</dd></div><div><dt>Resolved entities</dt><dd>{workflow.intent.affectedEntities.length}</dd></div></dl>{workflow.intent.affectedEntities.map((item) => <p key={item.entityId}><strong>{item.name}</strong> — {item.reason}</p>)}</div>; }
function SpecSummary({ workflow }: { workflow: DevelopmentWorkflowSnapshot }): React.JSX.Element { const spec = workflow.specification!; return <div className="summary-card"><h2>{spec.title}</h2><p>{spec.objective}</p><dl><div><dt>Status</dt><dd>{spec.status}</dd></div><div><dt>Revision</dt><dd>{spec.revision}</dd></div><div><dt>Requirements</dt><dd>{spec.requirements.length}</dd></div><div><dt>Criteria</dt><dd>{spec.acceptanceCriteria.length}</dd></div></dl><Details title="Scope" values={[...spec.scope.included, ...spec.scope.expectedFiles]}/><Details title="Constraints" values={spec.constraints}/><Details title="Acceptance criteria" values={spec.acceptanceCriteria.map((item) => `${item.id}: ${item.description}`)}/><Details title="Tests and risks" values={[...spec.testStrategy.requiredTests, ...spec.testStrategy.risks]}/></div>; }
function SpecificationControls({ workflow, busy, bridge, act }: { workflow: DevelopmentWorkflowSnapshot; busy: boolean; bridge: HostBridge; act: (operation: () => Promise<DevelopmentWorkflowSnapshot>) => void }): React.JSX.Element {
  const specification = workflow.specification!; const [constraint, setConstraint] = useState(""); const [resolutions, setResolutions] = useState<Record<string, string>>({});
  return <div className="spec-controls">{specification.decisions.filter((item) => !item.resolution).map((decision) => <label key={decision.id}><strong>{decision.blocking ? "Blocking decision" : "Decision"}: {decision.question}</strong><textarea value={resolutions[decision.id] ?? ""} onChange={(event) => setResolutions((current) => ({ ...current, [decision.id]: event.target.value }))}/><button disabled={busy || !(resolutions[decision.id] ?? "").trim()} onClick={() => act(() => bridge.request("workflow/spec/resolveDecision", { workflowId: workflow.id, decisionId: decision.id, resolution: resolutions[decision.id]! }))}>Resolve decision</button></label>)}<label><strong>Add an approved constraint as a material revision</strong><textarea value={constraint} onChange={(event) => setConstraint(event.target.value)} placeholder="Describe the constraint and why it is required."/><button disabled={busy || !constraint.trim()} onClick={() => act(() => bridge.request("workflow/spec/revise", { workflowId: workflow.id, reason: "User-edited specification constraint", patch: { constraints: [...specification.constraints, constraint.trim()] } }))}>Create revision</button></label><div className="button-row"><button disabled={busy} onClick={() => act(() => bridge.request("workflow/spec/submit", { workflowId: workflow.id }))}>Submit for review</button><button disabled={busy || !["draft", "awaiting-review"].includes(specification.status)} className="primary-button" onClick={() => act(() => bridge.request("workflow/spec/approve", { workflowId: workflow.id, expectedRevision: specification.revision }))}>Approve revision</button><button disabled={busy || specification.status !== "approved"} onClick={() => act(() => bridge.request("workflow/tasks/generate", { workflowId: workflow.id }))}>Generate reviewed task plan</button></div></div>;
}
function Details({ title, values }: { title: string; values: string[] }): React.JSX.Element { return <details><summary>{title} ({values.length})</summary><ul>{values.map((item, index) => <li key={`${index}:${item}`}>{item}</li>)}</ul></details>; }
function TaskList({ workflow }: { workflow: DevelopmentWorkflowSnapshot }): React.JSX.Element { return <div className="task-list">{workflow.tasks.map((task, index) => <article key={task.id}><span>{index + 1}</span><div><strong>{task.title}</strong><small>{task.status} · {task.dependencies.length} dependencies · {task.acceptanceCriterionIds.join(", ")}</small><p>{task.objective}</p>{task.staleReasons.map((reason) => <em key={reason}>{reason}</em>)}</div></article>)}</div>; }
function CapabilitySummary({ capabilities }: { capabilities?: CopilotCapabilities }): React.JSX.Element { if (!capabilities) return <p>Capabilities not detected.</p>; return <p className="capability-line">Copilot {capabilities.extensionDetected ? "detected" : "absent"} · chat {yes(capabilities.chatAvailable)} · discovery {yes(capabilities.agentDiscoveryAvailable)} · direct {yes(capabilities.directInvocationAvailable)} · insertion {yes(capabilities.promptInsertionAvailable)}</p>; }
function ContextPanel({ context, busy, onPin, onRemove, onRestore }: { context?: TaskContextPackage; busy: boolean; onPin: (id: string, pinned: boolean) => void; onRemove: (id: string) => void; onRestore: (id: string) => void }): React.JSX.Element { if (!context) return <Empty value="Build context from the selected ready task."/>; return <div className="context-preview"><div className="fingerprint"><span>{context.completeness} · {context.estimatedTokens.toLocaleString()} estimated tokens · {context.items.length} included</span><code>{context.contentFingerprint}</code></div>{context.diagnostics.map((item) => <p key={`${item.code}:${item.message}`} className={`diagnostic ${item.severity}`}>{item.message}</p>)}{context.items.map((item) => <article key={item.id}><header><strong>{item.title}</strong><span>{item.tier} · {item.compression}</span></header><p>{item.reason}</p><pre>{item.content.slice(0, 1200)}</pre><div className="button-row"><button disabled={busy} onClick={() => onPin(item.id, !item.pinned)}>{item.pinned ? "Unpin" : "Pin"}</button><button disabled={busy || item.required} onClick={() => onRemove(item.id)}>Remove</button></div></article>)}{!!context.exclusions.length && <details><summary>Removed candidates ({context.exclusions.length})</summary>{context.exclusions.map((entry) => <button key={entry.item.id} disabled={!entry.restorable} onClick={() => onRestore(entry.item.id)}>Restore {entry.item.title} · {entry.reason}</button>)}</details>}</div>; }
function PromptPanel({ prepared, session, execution, busy, onApprove, onCopy, onStart, onTrack, onConfirmStarted, onConfirmStopped, onCancel }: { prepared: PreparedDelegation; session?: DelegationSession; execution?: TaskExecutionSession; busy: boolean; onApprove: () => void; onCopy: () => void; onStart: () => void; onTrack: () => void; onConfirmStarted: () => void; onConfirmStopped: () => void; onCancel: () => void }): React.JSX.Element { return <div className="prompt-panel"><div className="fingerprint"><span>{prepared.approved ? "Approved prompt" : "Awaiting prompt approval"}</span><code>{prepared.promptFingerprint}</code></div><pre>{prepared.prompt}</pre><div className="button-row"><button disabled={busy || prepared.approved} onClick={onApprove}>Approve exact prompt</button><button disabled={busy || !prepared.approved} onClick={onCopy}>Copy approved prompt</button><button disabled={busy || !prepared.approved || Boolean(session)} className="primary-button" onClick={onStart}>Start controlled delegation</button></div>{session && <><p className="session-status">{session.mode} · {session.status} · completion is not claimed</p><div className="button-row"><button disabled={busy || Boolean(execution)} onClick={onTrack}>Create execution tracker</button><button disabled={busy || session.status === "executing"} onClick={onConfirmStarted}>Confirm external start</button><button disabled={busy} onClick={onConfirmStopped}>Confirm external stop</button><button disabled={busy || session.status === "cancelled"} onClick={onCancel}>Stop Keystone tracking</button></div>{execution && <p>Execution tracker {execution.status}. Open Validation to observe changes, capture results, and validate.</p>}</>}</div>; }
function Empty({ value }: { value: string }): React.JSX.Element { return <div className="honesty-note"><span>{value}</span></div>; }
function ErrorText({ value }: { value: string }): React.JSX.Element { return <div className="error-banner" role="alert">{value}</div>; }
function yes(value: boolean): string { return value ? "available" : "unavailable"; }
function show(setter: (value: string) => void): (cause: unknown) => void { return (cause) => setter(cause instanceof Error ? cause.message : String(cause)); }
