export const UNIVERSAL_ADAPTER_VERSIONS: Readonly<Record<string, string>> = {
  "keystone.adapter.language.java": "1.0.0",
  "keystone.adapter.language.python": "1.0.0",
  "keystone.adapter.language.csharp": "1.0.0",
  "keystone.adapter.language.go": "1.0.0",
  "keystone.adapter.language.rust": "1.0.0",
  "keystone.adapter.language.c": "1.0.0",
  "keystone.adapter.language.cpp": "1.0.0",
  "keystone.adapter.language.ruby": "1.0.0",
  "keystone.adapter.language.php": "1.0.0",
  "keystone.adapter.language.kotlin": "1.0.0",
  "keystone.adapter.language.swift": "1.0.0",
  "keystone.adapter.language.shell": "1.0.0",
  "keystone.adapter.documentation": "1.0.0",
  "keystone.adapter.contract": "1.0.0",
  "keystone.adapter.framework": "1.0.0",
  "keystone.adapter.database.sql": "1.0.0",
  "keystone.adapter.orm": "1.0.0",
  "keystone.adapter.test-framework": "1.0.0",
  "keystone.adapter.build-package": "1.0.0",
  "keystone.adapter.ci": "1.0.0",
  "keystone.adapter.infrastructure": "1.0.0",
  "keystone.adapter.configuration": "1.0.0",
  "keystone.adapter.fallback": "1.0.0",
  "keystone.adapter.cross-technology": "1.0.0",
};
