import { createHash } from 'node:crypto';
import { KEYSTONE_OKF_PROFILE, KEYSTONE_OKF_PROFILE_DIGEST } from './profile';
import type { KeystoneOkfSnapshot, OkfConfidence, OkfProvenance } from './types';
export interface OkfValidationIssue { readonly path:string; readonly message:string; }
export interface OkfValidationResult { readonly valid:boolean; readonly issues:readonly OkfValidationIssue[]; }
const iso=(value:string):boolean=>Number.isFinite(Date.parse(value));
function required(path:string,record:Record<string,unknown>,fields:readonly string[],issues:OkfValidationIssue[]):void{for(const field of fields)if(!(field in record)||record[field]===undefined||record[field]==='')issues.push({path:`${path}.${field}`,message:'Required.'});}
function confidence(path:string,value:OkfConfidence,issues:OkfValidationIssue[]):void{if(!value||!Number.isFinite(value.score)||value.score<0||value.score>1)issues.push({path:`${path}.score`,message:'Must be between 0 and 1.'});if(!['observed','derived','inferred'].includes(value?.level))issues.push({path:`${path}.level`,message:'Unsupported confidence level.'});}
function provenance(path:string,value:OkfProvenance,workspaceId:string,runId:string,issues:OkfValidationIssue[]):void{if(!value){issues.push({path,message:'Required.'});return;}if(value.workspaceId!==workspaceId)issues.push({path:`${path}.workspaceId`,message:'Workspace mismatch.'});if(value.extractionRunId!==runId)issues.push({path:`${path}.extractionRunId`,message:'Extraction run mismatch.'});if(!iso(value.observedAt))issues.push({path:`${path}.observedAt`,message:'Invalid timestamp.'});}
const digest=(value:unknown):string=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
export function validateOkfSnapshot(snapshot:KeystoneOkfSnapshot):OkfValidationResult{
 const issues:OkfValidationIssue[]=[]; const m=snapshot.manifest;
 if(m.profile!==KEYSTONE_OKF_PROFILE.id)issues.push({path:'manifest.profile',message:`Expected ${KEYSTONE_OKF_PROFILE.id}.`});
 if(m.profileVersion!==KEYSTONE_OKF_PROFILE.version)issues.push({path:'manifest.profileVersion',message:`Expected ${KEYSTONE_OKF_PROFILE.version}.`});
 if(m.profileDigest!==KEYSTONE_OKF_PROFILE_DIGEST)issues.push({path:'manifest.profileDigest',message:'Profile digest mismatch.'});
 if(!iso(m.generatedAt))issues.push({path:'manifest.generatedAt',message:'Invalid timestamp.'});
 const unitIds=new Set<string>(),canonical=new Set<string>(),evidenceIds=new Set<string>(),relationshipIds=new Set<string>(),observationIds=new Set<string>();
 snapshot.evidence.forEach((item,index)=>{const p=`evidence[${index}]`;if(evidenceIds.has(item.id))issues.push({path:`${p}.id`,message:'Duplicate ID.'});evidenceIds.add(item.id);if(!item.source.workspaceRelativePath)issues.push({path:`${p}.source.workspaceRelativePath`,message:'Required.'});if(item.source.workspaceRelativePath.startsWith('/')||/^[A-Za-z]:\\/.test(item.source.workspaceRelativePath))issues.push({path:`${p}.source.workspaceRelativePath`,message:'Must be workspace-relative.'});if(!iso(item.observedAt))issues.push({path:`${p}.observedAt`,message:'Invalid timestamp.'});if(item.freshness === 'current' && item.extractionRunId!==m.extractionRunId)issues.push({path:`${p}.extractionRunId`,message:'Current evidence run mismatch.'});});
 snapshot.units.forEach((item,index)=>{const p=`units[${index}]`;required(p,item as unknown as Record<string,unknown>,KEYSTONE_OKF_PROFILE.requiredUnitFields,issues);if(unitIds.has(item.id))issues.push({path:`${p}.id`,message:'Duplicate ID.'});unitIds.add(item.id);const ck=`${item.kind}:${item.canonicalKey}`;if(item.lifecycle!=='deleted'&&canonical.has(ck))issues.push({path:`${p}.canonicalKey`,message:'Duplicate active canonical key.'});canonical.add(ck);if(!KEYSTONE_OKF_PROFILE.knowledgeKinds.includes(item.kind))issues.push({path:`${p}.kind`,message:'Unsupported kind.'});if(!iso(item.createdAt)||!iso(item.updatedAt)||!iso(item.firstSeenAt)||!iso(item.lastSeenAt))issues.push({path:p,message:'Invalid lifecycle timestamp.'});confidence(`${p}.confidence`,item.confidence,issues);provenance(`${p}.provenance`,item.provenance,m.workspaceId,m.extractionRunId,issues);});
 const byId=new Map(snapshot.units.map(item=>[item.id,item]));
 snapshot.relationships.forEach((item,index)=>{const p=`relationships[${index}]`;required(p,item as unknown as Record<string,unknown>,KEYSTONE_OKF_PROFILE.requiredRelationshipFields,issues);if(relationshipIds.has(item.id))issues.push({path:`${p}.id`,message:'Duplicate ID.'});relationshipIds.add(item.id);const source=byId.get(item.sourceId),target=byId.get(item.targetId);if(!source)issues.push({path:`${p}.sourceId`,message:'Unknown source.'});if(!target)issues.push({path:`${p}.targetId`,message:'Unknown target.'});if(!KEYSTONE_OKF_PROFILE.relationshipKinds.includes(item.kind))issues.push({path:`${p}.kind`,message:'Unsupported kind.'});const rule=KEYSTONE_OKF_PROFILE.relationshipConstraints[item.kind];if(rule&&source&&!rule.sources.includes(source.kind))issues.push({path:`${p}.sourceId`,message:`${source.kind} is not an allowed source for ${item.kind}.`});if(rule&&target&&!rule.targets.includes(target.kind))issues.push({path:`${p}.targetId`,message:`${target.kind} is not an allowed target for ${item.kind}.`});confidence(`${p}.confidence`,item.confidence,issues);provenance(`${p}.provenance`,item.provenance,m.workspaceId,m.extractionRunId,issues);});
 snapshot.observations.forEach((item,index)=>{const p=`observations[${index}]`;required(p,item as unknown as Record<string,unknown>,KEYSTONE_OKF_PROFILE.requiredObservationFields,issues);if(observationIds.has(item.id))issues.push({path:`${p}.id`,message:'Duplicate ID.'});observationIds.add(item.id);if(!byId.has(item.subjectId))issues.push({path:`${p}.subjectId`,message:'Unknown subject.'});if(!/^[a-z][a-z0-9+.-]*:[A-Za-z0-9._-]+$/.test(item.predicate))issues.push({path:`${p}.predicate`,message:'Predicate must be namespaced.'});if(!iso(item.observedAt))issues.push({path:`${p}.observedAt`,message:'Invalid timestamp.'});confidence(`${p}.confidence`,item.confidence,issues);provenance(`${p}.provenance`,item.provenance,m.workspaceId,m.extractionRunId,issues);});
 for(const [p,records] of [['units',snapshot.units],['relationships',snapshot.relationships],['observations',snapshot.observations]] as const)for(const [index,item] of records.entries())for(const id of item.provenance.evidenceIds)if(!evidenceIds.has(id))issues.push({path:`${p}[${index}].provenance.evidenceIds`,message:`Unknown evidence ${id}.`});
 const active=snapshot.units.filter(x=>x.lifecycle==='active').length,deleted=snapshot.units.filter(x=>x.lifecycle==='deleted').length; const expected={units:snapshot.units.length,relationships:snapshot.relationships.length,observations:snapshot.observations.length,evidence:snapshot.evidence.length,active,deleted};for(const [key,value] of Object.entries(expected))if(m.counts[key as keyof typeof expected]!==value)issues.push({path:`manifest.counts.${key}`,message:`Expected ${value}.`});
 const actual={units:digest(snapshot.units),relationships:digest(snapshot.relationships),observations:digest(snapshot.observations),evidence:digest(snapshot.evidence)};for(const [key,value] of Object.entries(actual))if(m.digests[key]!==value)issues.push({path:`manifest.digests.${key}`,message:'Digest mismatch.'});
 return{valid:issues.length===0,issues};
}
